name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Develop

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install root dependencies
        run: npm install

      - name: Install wait-on
        run: npm install -g wait-on

      - name: Install client and server dependencies
        run: |
          cd client
          npm install
          cd ../server
          npm install
          cd ..

      - name: Build backend
        run: |
          cd server
          npm run build
          cd ..

      - name: Start dev servers and wait for backend
        run: |
          npm run develop &
          wait-on http://localhost:3001

      - name: Run Cypress tests
        run: npm run cypress:run

  deploy:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Develop
    steps:
      - name: Deploy to Render
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }}









