name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Develop
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install all dependencies
        run: npm run install

      - name: Install wait-on
        run: npm install -g wait-on

      - name: Start dev servers and wait for backend
        run: |
          npm run develop &
          wait-on http://localhost:3001

      - name: Run Cypress tests
        run: npm run cypress:run

  deploy:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Develop
    steps:
      - name: Deploy to Render
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }}






