name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Develop
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install root dependencies
        run: npm install

      - name: Install client and server dependencies
        run: |
          cd client && npm install
          cd ../server && npm install

      - name: Start dev servers
        run: |
          cd server && npm run watch &
          cd ../client && npm run dev &
          sleep 10

      - name: Run Cypress tests
        run: npm run cypress:run

  deploy:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Develop
    steps:
      - name: Deploy to Render
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
